version: "3"

services:
  wrk:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./results:/results
    env_file:
      - .env
    environment:
      - servers= adonis express express-cluster express-forked fastify fastify-cluster fastify-forked golang golang-goroutines rust
    depends_on:
        - adonis
        - express
        - express-cluster
        - express-forked
        - fastify
        - fastify-cluster
        - fastify-forked
        - golang
        - golang-goroutines
        - rust
  adonis:
    build:
      context: ./projects/adonis
      dockerfile: ./Dockerfile
  express:
    build:
      context: ./projects/express
      dockerfile: ./Dockerfile
  express-cluster:
    build:
      context: ./projects/express-cluster
      dockerfile: ./Dockerfile
  express-forked:
    build:
      context: ./projects/express-forked
      dockerfile: ./Dockerfile
  fastify:
    build:
      context: ./projects/fastify
      dockerfile: ./Dockerfile
  fastify-cluster:
    build:
      context: ./projects/fastify-cluster
      dockerfile: ./Dockerfile
  fastify-forked:
    build:
      context: ./projects/fastify-forked
      dockerfile: ./Dockerfile
  golang:
    build:
      context: ./projects/golang
      dockerfile: ./Dockerfile
  golang-goroutines:
    build:
      context: ./projects/golang-goroutines
      dockerfile: ./Dockerfile
  rust:
    build:
      context: ./projects/rust
      dockerfile: ./Dockerfile
