version: "3"

services:
  wrk:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./results:/results
    depends_on:
      - express
      - express-cluster
      - express-forked
      - fastify
      - fastify-cluster
      - fastify-forked
      - golang
      - golang-goroutines

  express:
    build:
      context: ./express
      dockerfile: ./Dockerfile

  express-cluster:
    build:
      context: ./express-cluster
      dockerfile: ./Dockerfile

  express-forked:
    build:
      context: ./express-forked
      dockerfile: ./Dockerfile

  fastify:
    build:
      context: ./fastify
      dockerfile: ./Dockerfile

  fastify-cluster:
    build:
      context: ./fastify-cluster
      dockerfile: ./Dockerfile

  fastify-forked:
    build:
      context: ./fastify-forked
      dockerfile: ./Dockerfile

  golang:
    build:
      context: ./golang
      dockerfile: ./Dockerfile

  golang-goroutines:
    build:
      context: ./golang-goroutines
      dockerfile: ./Dockerfile
